---
title: "Team"
---

List of the current members of the working group (alphabetically ordered):

-   Andreas Leich, German Aerospace Center (DLR), Email address: andreas.leich at dlr.de;
-   Bidisha Ghosh, Trinity College Dublin, Email address: bghosh at tcd.ie;
-   Caroline Alméras, The European Conference of Transport Research Institutes (ECTRI), Email address: caroline.almeras at ectri.org;
-   Cathy Wu, Massachusetts Institute of Technology (MIT), Email address: cathywu at mit.edu;
-   Christine Buisson, Université Gustave Eiffel, Email address: Chrchristine.buisson at univ-eiffel.fr;
-   Danjue Chen, North Carolina State University, Email address: dchen33 at ncsu.edu;
-   Elizabeth Sall, UrbanLabs LLC, Email: easall at gmail.com;
-   Evangelos Mitsakis, Centre for Research and Technology Hellas - Hellenic Institute of Transport, Email address: emit at certh.gr;
-   Irene Martínez Josemaría, TU Delft, Email address: I.MartinezJosemaria at tudelft.nl;
-   Jiwon Kim, University of Queensland, Email address: jiwon.kim at uq.edu.au;
-   Junyi Ji,Vanderbilt University, Email address: junyi.ji at vanderbilt.edu;
-   Kendra Levine, UC Berkeley, Email address : kklevine at berkeley.edu;
-   Liming Wang, Portland State University, Email address:limwang at pdx.edu;
-   Marcello Montanino, University of Naples Federico II, Email address: marcello.montanino at unina.it;
-   Nicolas Saunier, Polytechnique Montréal, Email address: nicolas.saunier at polymtl.ca;
-   Peggi Knight, Iowa Department of Transportation, Email: peggi.knight at iowadot.us;
-   Peter Wagner, German Aerospace Center (DLR), Email address: peter.wagner at dlr.de;
-   Shimul (Md. Mazharul) Haque, Queensland University of Technology, Email address: m1.haque at qut.edu.au;
-   Silvia Francesca Varotto, École Nationale des Travaux Publics de l'État, Email address: SilviaFrancesca.Varotto at entpe.fr;
-   Vincenzo Punzo, University of Naples Federico II, Email address: vinpunzo at unina.it;
-   Xuesong Zhou, Arizona State University, Email address: xuesong.zhou at asu.edu;
-   Yinhai Wang, University of Washington, Email address: yinhai at uw.edu;
-   Zuduo Zheng, University of Queensland, Email address: zuduo.zheng at uq.edu;
